[package]
name = "chippy"
version = "1.0.0"
edition = "2021"
description = "A simple and lightweight CHIP-8 emulator"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.58"
byteorder = "1.4.3"
clap = { version = "3.2.10", features = ["derive"] }
fastrand = "1.7.0"
fixedbitset = "0.4.2"
macroquad = "0.3.23"
thiserror = "1.0.31"
